<a href="https://colab.research.google.com/github/AvaniTheCoder/Machine-Learning-Practice/blob/main/Day2_11_8_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#variables
names= "Alice"
age= 25
# Data types: int, float, string
height = 5.8
is_student = True

#Type conversion
age_as_str = str(age)
height_as_int = int(height)
print(height_as_int)
print(age_as_str)
print(type(height_as_int))

#if statements


5
25
<class 'int'>


In [ ]:
temperature = 20
if temperature > 25:
  print("It's hot outside")
else:
  print("It's not hot outside")

It's not hot outside


In [ ]:
for i in range(5):
   print("Iteration",5)

Iteration 5
Iteration 5
Iteration 5
Iteration 5
Iteration 5


In [ ]:
i=0
while i<5:
  print("Iteration",i)
  i=i+1

Iteration 0
Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [ ]:
i = 1
while i<19:
  print ("Your age is",i)
  i=i+1

Your age is 1
Your age is 2
Your age is 3
Your age is 4
Your age is 5
Your age is 6
Your age is 7
Your age is 8
Your age is 9
Your age is 10
Your age is 11
Your age is 12
Your age is 13
Your age is 14
Your age is 15
Your age is 16
Your age is 17
Your age is 18


In [ ]:
  if age <18:
    print("You are not a child")
  else:
    print("You are a child")

You are not a child


In [ ]:
  age = int(input("Enter your age:"))
  if age <= 18:
    print("You are allowed to drive")
  else:
    print("You are not allowed to drive")

Enter your age:20
You are not allowed to drive


In [ ]:
def greetings(name):
  print("Hello "+name+ " Good Morning")
name = input("Enter your name")
greetings(name)

Enter your nameGauri
Hello Gauri Good Morning


In [ ]:
def sum(a,b):
  print("Sum = ",a+b)
sum(10,20)

Sum =  30


In [ ]:

def mul(p,q):
  m=p*q
  return m
mul(2,2)

4

In [ ]:
def goodbye(name):
  return "Bye, "+name
goodbye("Gauri")

'Bye, Gauri'

In [ ]:
def divide_by_ten(n):
  d=n/10
  return d
divide_by_ten(100)

10.0

In [ ]:
import math
radius = 5
area = math.pi*radius*radius
print("area =",area )

area = 78.53981633974483


In [ ]:
import numpy as np
# creating arrays
arr = np.array([1,2,3,4,5])

#Array operations
arr_squared = arr **2
sum_of_elements = np.sum(arr)
mean_value = np.mean(arr)
print(arr_squared)
print(sum_of_elements)
print(mean_value)

#indexing and slicing
subset = arr[1:4]
print(subset)

#mathematical functions
sin_values = np.sin(arr)
print(sin_values)

#Multidimentional arrays
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)
matrix_transposed = matrix.T
print(matrix_transposed)


[ 1  4  9 16 25]
15
3.0
[2 3 4]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# HW: Create a table with 5 rows and 5 columns
import pandas as pd

# Creating DataFrames
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25,30,28]}
df = pd.DataFrame(data)

#Accessing data
name_column = df['Name']
ages = df['Age']

#Filtering data
young_people = df[df['Age']<30]

#aggregation
average_age = df['Age'].mean()

#Handling missiog data
df_missing  = pd.DataFrame({'A':[1,2,np.nan,4]})# creating another dataframe with empty value
df_cleaned = df_missing.dropna() # removing the empty value
df
df_missing
young_people
df_cleaned

A
0  1.0
1  2.0
3  4.0

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie','Gauri','Deepali'],
        'Maths': [25,30,28,27,24],
        'English': [25,30,30,30,28],
        'Hindi': [24,26,25,27,28],
        'Marathi':[23,24,25,25,26]}
df = pd.DataFrame(data)
data_filter = df[df['Maths']>25]
df
data_filter

Name  Maths  English  Hindi  Marathi
1      Bob     30       30     26       24
2  Charlie     28       30     25       25
3    Gauri     27       30     27       25